---
# Permit co-located instances for solitary minikube virtual machines.
antiAffinity: "soft"

# Shrink default JVM heap.
esJavaOpts: "-Xmx128m -Xms128m"

# Allocate smaller chunks of memory per pod.
resources:
  requests:
    cpu: "100m"
    memory: "512M"
  limits:
    cpu: "1000m"
    memory: "512M"

# Request smaller persistent volumes.
volumeClaimTemplate:
  accessModes: [ "ReadWriteOnce" ]
  storageClassName: "hostpath"
  resources:
    requests:
      storage: 100M

lifecycle:
  postStart:
    exec:
      command:
        - bash
        - -c
        - |
          #!/bin/bash
          # Add a template to adjust number of shards/replicas
          TEMPLATE_NAME=dc-content-template
          INDEX_PATTERN="dc-content-*"
          SHARD_COUNT=8
          REPLICA_COUNT=1
          ES_URL=http://localhost:9200
          while [[ "$(curl -s -o /dev/null -w '%{http_code}\n' $ES_URL)" != "200" ]]; do sleep 1; done
          curl --location --request PUT "$ES_URL/_index_template/$TEMPLATE_NAME" --header 'Content-Type: application/json'  --data-raw '{ "index_patterns": ['\""$INDEX_PATTERN"\"'], "template": { "settings": { "index": { "number_of_shards": '$SHARD_COUNT', "number_of_replicas": '$REPLICA_COUNT' } }, "mappings": { "properties": { "content": { "dynamic": "true", "properties": { "commentCount": { "type": "text" }, "content": { "type": "text" }, "contentNum": { "type": "integer" }, "dt": { "type": "date", "format": "strict_date_optional_time||epoch_millis||YYYY.MM.DD HH:mm:ss" }, "ip": { "type": "keyword" }, "nickname": { "type": "keyword" }, "recommendCount": { "type": "text" }, "replyList": { "dynamic": "true", "properties": { "content": { "type": "text" }, "date": { "type": "text" }, "id": { "type": "integer", "ignore_malformed": false, "coerce": true }, "innerReplyList": { "properties": { "content": { "type": "text" }, "date": { "type": "text" }, "ip": { "type": "keyword" }, "nickname": { "type": "keyword" } } }, "ip": { "type": "keyword" }, "nickname": { "type": "keyword" } } }, "title": { "type": "text" }, "url": { "type": "text" }, "viewCount": { "type": "text" } } }, "htmlMeta": { "properties": { "htmlLength": { "type": "integer" }, "outgoingLinkCount": { "type": "integer" }, "textLength": { "type": "integer" } } } } } } }'